services:

  backend:
    build: ./backend

    environment:
      VLLM_EMBED_URL: ${VLLM_EMBED_URL}
      DATABASE_URL: ${DATABASE_URL}

  vllm-embed:
    image: vllm/vllm-openai:v0.29.0-cu129
    ports:
      - "7000:8000" # remove when deploying, only for host to talk to it, ie testing
    
    gpus:
      - driver: nvidia
        device_ids: ["2"]
        capabilities: [gpu]

    volumes:
      - ./models/qwen3-embedding-4b:/models/qwen3-embedding-4b:ro

    command: 
      - --model
      - ${VLLM_EMBED_MODEL}
      - --gpu-memory-utilization
      - "0.15" # 15% of 80GB
    