"""added max char to hash, changed some columns in batch to allow null

Revision ID: 19192640926a
Revises: 20260917_0001
Create Date: 2026-09-21 02:05:12.193828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19192640926a'
down_revision: Union[str, Sequence[str], None] = '20260917_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'content_hash',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
