"""added translated columns in article table for future proofing

Revision ID: 62e573ed0016
Revises: 19192640926a
Create Date: 2026-09-21 04:15:43.273025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e573ed0016'
down_revision: Union[str, Sequence[str], None] = '19192640926a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('translatedTitle', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('translatedContent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'translatedContent')
    op.drop_column('articles', 'translatedTitle')
    # ### end Alembic commands ###
